application: scriptingserver
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: index.html
  upload: index.html

- url: /end
  script: server.application
  
libraries:
- name: webapp2
  version: latest